### ISSUE TITLE
info box with elevation, surface, max_speed

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#12]

**Comment by easbar** [comment]
## current features

Currently the elevation diagram has the following features:

* shows the elevation along the current route as a line graph
* hovering the graph shows the x/y values (distance/elevation) in a popup window, it also shows the 'segment length' and the 'type', but this information only really makes sense when path details are shown (see below)
 
![image](https://user-images.githubusercontent.com/17603532/112119876-0f334f00-8bbe-11eb-9e0a-0a0c858de465.png)

* hovering the graph also shows the current position as a popup positioned on the route that is displayed on the map
 
![image](https://user-images.githubusercontent.com/17603532/112119929-19554d80-8bbe-11eb-9a7c-d2f80f850128.png)

* dragging the cursor in x-direction above the diagram selects an x-range and the map is zoomed to the corresponding part of the route. Clicking the diagram again removes the selection and the map is zoomed out to show the entire route again.

* there is an error icon on the right y-axis of the diagram that can be used to select an elevation value (shown as horizontal line in the diagram). All parts of the route that are above this elevation are highlighted in red: 

![image](https://user-images.githubusercontent.com/17603532/112120458-8b2d9700-8bbe-11eb-92bd-921ac5f508f3.png)

* there is a 'Legend' label that displays the legend when we hover over it:

![image](https://user-images.githubusercontent.com/17603532/112120808-e2cc0280-8bbe-11eb-9c10-8eb305295ebb.png)

  For elevation this makes no sense, because we should rather show it unconditionally or even do not show it at all since it has only one entry. When path details are shown it is useful however.

* when path details are enabled there two arrow buttons are shown that can be used to switch between the shown path details: 

![image](https://user-images.githubusercontent.com/17603532/112121371-7b628280-8bbf-11eb-9bbf-29ced877a31f.png)

The y-axis always shows the elevation, regardless of the selected path detail. The value of the selected path detail (here: road_class) is visualized by the coloring underneath the elevation line graph. The popup window's type and segment length fields now make sense and show the value of the path detail and the length of the corresponding route segment. The path detail value is also shown by the popup on the map. The legend is now useful (compared to the case when we only show elevation), but it might become too large when there are too many values:

![image](https://user-images.githubusercontent.com/17603532/112121774-e90eae80-8bbf-11eb-9ffd-ee5a12ccc20e.png)

However, we only use eight different colors for the graph coloring anyway.

* some path details are not enum-like (like road_class or surface), but the value is numeric (like average_speed or time). In this case the path detail value is visualized using a linear color gradient (from blue to red) while the y-axis still shows the elevation:
 
![image](https://user-images.githubusercontent.com/17603532/112122093-37bc4880-8bc0-11eb-9e90-cd9b52493001.png)

The legend is disabled for numeric values, but it would be useful to show the value range.

## missing features

a few things that could be improved (even without changing the entire concept):

* use all available space in x-direction
* allow zooming the graph (otherwise elevation details are hard to resolve for longer routes)

**Comment by easbar** [comment]
I did a proof of concept here: https://github.com/graphhopper/graphhopper-maps/tree/heightgraph

The path details are shown for hard-coded values (surface, road_environment, average_speed) and we can switch between the different route alternatives as well (this was easy to do thanks to Janek's nice app architecture :))
