### ISSUE TITLE
dragging or zooming a raster map like OpenStreetMap hides the routes

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#122]
This is a strange bug as it works for all vector tiles.

**Comment by easbar** [comment]
Apparently this was introduced by #87

**Comment by karussell** [comment]
Strange, for "Maptiler Satellite" this works fine although I think that these are raster tiles too (?)

**Comment by easbar** [comment]
Ok, I'll try to create a minimal example for this.

**Comment by easbar** [comment]
https://github.com/visgl/react-map-gl/issues/1530

**Comment by easbar** [comment]
The problem is here: https://github.com/graphhopper/graphhopper-maps/blob/3f7e9830a540875bd098d3d6efe5631121298044/src/map/Map.tsx#L29

With each call of `Map#render` we create a new style object and the map is draw again which leads to the flickering. We get the `mapStyle` option from the `MapOptionsStore` and this is just a constant so it will always be the same object for a given style. However, in `mapStyle` we wrap these constant objects into new ones that are created over and over again.

@Janekdererste any idea how we should fix this? I guess we could 'cache' the objects we produce in `getStyle`, but that does not seem like such a great idea. Or we create the ready to be used (MapBox) mapStyle objects right in the `MapOptionsStore` once and for all. The code kind of looks like you were trying to make the data in `MapOptionsStore` not related to Mapbox or why do we even have this `StyleOption` interface? Otherwise I think I would rather create an interface for the Mapbox style (one for vector and one for raster) and there would be nothing we need to wrap in the first place?
Or maybe react has a some built-in feature that allows 'transforming' a state object (like `mapStyle`) without re-creating new objects all the time? Maybe `React.memo()`?

**Comment by Janekdererste** [comment]
Yes, the code in ```getStyle()``` was copied from the former Mapbox class where it was only run once when the map was created. The code in ```MapOptionsStore``` is supposed to be independent of Mapbox.  I felt like the stores should be independent of the visualization details and the view components should transform our custom data model into whatever they needed to cater their APIs. 

I don't insist on keeping it this way. 

1. Setting Mapbox Layers in the ```MapOptionsStore``` sounds pragmatic and would solve the re-rendering issue. 
2. Another way would be to have the Mapbox style in a state, which is only updated when the Style store changes. I think that is your suggestion from the last paragraph
```
const [style, setStyle = useState(getStyle(mapStyle))
useState(() => setStyle(getStyle(mapStyle)), [mapStyle])
```

It feels like both approaches have different drawbacks.

**Comment by Janekdererste** [comment]
Having thought about it a little more, I'd prefer option 2, since it would require the least amount of re-structuring and seems like a simple fix.

**Comment by easbar** [comment]
Option 1) is not as nice because then `MapOptionsStore`  somewhat depends on Mapbox details. Then again, it already depends on this a bit anyway. Just the fact that there are Raster- and Vectorlayers and Vectorlayers only need a url pointing to a (Mapbox)style json file is already Mapbox specific. The react mapbox wrapper already provides an abstraction on top of the map library implementation (e.g. Mapbox vs Maplibre) so I'm not sure if further abstracting the layer details is really required. 

Option 2) is a bit ugly, because we need this `useState` stuff just to prevent re-rendering...

> and the view components should transform our custom data model into whatever they needed to cater their APIs.

Yes, except this 'transformation' cannot be done without using `useState` in the components? To me it seems quite logical that sometimes such transformations are needed, so not sure if we should adjust our store data to get rid of them...

> Having thought about it a little more, I'd prefer option 2, since it would require the least amount of re-structuring and seems like a simple fix.

I don't have a strong preference, but I would probably have gone for option 1 :) 

There is also this issue: https://github.com/graphhopper/graphhopper-maps/commit/5e2b89aaa9610223fe398b9ce196185f67e2476b#r53725724 and I wonder if we should even use the `mapStyle` field in `Map.tsx`. I think we can also set it to 

```javascript
{
  version: 8,
  sources: {},
  layers: []
}
```
and pass the 'background'/map layer via the `mapLayers` prop just like all the other layers. I'll try and come back here :)

**Comment by easbar** [comment]
> and pass the 'background'/map layer via the mapLayers prop just like all the other layers.

We could do this, but then we would need to setup all the layers ourselves. Since the Mapbox style typically contains very many layers this is also not ideal. But maybe all we would have to do is load the style json manually and then loop over the different layers. Maybe we have to do this anyway to find the first symbol layer id (see https://github.com/graphhopper/graphhopper-maps/commit/5e2b89aaa9610223fe398b9ce196185f67e2476b#commitcomment-53734397).

But for now I just went with the quick fix like you suggested to fix the flickering issue.
