### ISSUE TITLE
improve instructions

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#15]

**Comment by Janekdererste** [comment]
But keep it simple:
- Have a nicely formatted list
- Include turning icons if it's easy to include

**Comment by Janekdererste** [comment]
I have added the icons from the current gh client in png format. 

Since I saw that the icons are available as svg as well I would prefer to have them in that format. In the repo I only found all icons in one file though. Since I'm not familiar with any svg editor I gave up on extracting the icons into separate images after half an hour. Do we have anybody who can do this quickly?

Having those icons in svg format would make the icons resolution independent and possibly even smaller than the pngs. 

Also the start and finish icon are the markers from the old gh-client. I guess I'd have to replace them by our current ones. This task should be combined with #37 though since we'll have to have our own icons for that purpose anyway (I think) 

Maybe @karussell or @easbar want to comment on this.

**Comment by karussell** [comment]
> I gave up on extracting the icons into separate images after half an hour. 

What do you mean here? The SVG images are already separate there too: https://github.com/graphhopper/graphhopper/tree/master/web-bundle/src/main/resources/com/graphhopper/maps/img

(btw: for an editor I can recommend inkscape)

**Comment by Janekdererste** [comment]
> What do you mean here? The SVG images are already separate there too: https://github.com/graphhopper/graphhopper/tree/master/web-bundle/src/main/resources/com/graphhopper/maps/img

The turn instructions are in png format. And then there is a single svg which has all the turn icons. 

> (btw: for an editor I can recommend inkscape)

I used Inkscape, but since I never used the Program before it took me forever to get what I wanted. I guess I'll start learning it by designing my own 'close' symbol or so :-)

I guess I leave it as is and postpone svg turn Icons to a later point

**Comment by karussell** [comment]
Ah, I think not all vehicles are available as svg. Ups. Will add the missing there.

E.g. some are already:

https://github.com/graphhopper/graphhopper/blob/master/web-bundle/src/main/resources/com/graphhopper/maps/img/foot.svg

https://github.com/graphhopper/graphhopper/blob/master/web-bundle/src/main/resources/com/graphhopper/maps/img/motorcycle.svg
