### ISSUE TITLE
Indicate that vector tiles are slow

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#178]
In our map layers menu we still offer `MapTiler` and `Mapilion` even though the rendering of these vector tile layers is so slow they are hardly useful at all. At least it should be clear to users that choosing them will result in bad performance (if we do not remove them entirely).

We started this discussion here: https://github.com/graphhopper/graphhopper-maps/pull/176#discussion_r787968715

**Comment by karussell** [comment]
Not sure if this is very important. On my old laptop the vector tiles are not much slower than the ones via maplibre, probably because of the lack of a powerful graphic card. And also on a newer mobile Android device the vector tiles perform not bad (although not as fast as the raster tiles). (You can easily compare all layers e.g. via https://navi.graphhopper.org).

**Comment by easbar** [comment]
On my Laptop Maptiler is basically unusable with Firefox, but using Chrome it is actually not that bad. On my iPhone 7 it is so slow that quick scrolling/zooming is impossible for Firefox, Chrome and Safari. But sure since this is not the default we can just leave it like this and people will figure out that these layers are slower themselves. Shall we change the menu entries to `Maptiler (Vector)` and `Mapilion (Vector)`? Most people won't know what that means, but some might know and this way at least it's clear that they are of a different kind?

**Comment by Janekdererste** [comment]
On my iPhone 12 it asks whether it should close the page because it does too much computation 🙃

Anyway, I wouldn't show a warning.

> Shall we change the menu entries to Maptiler (Vector) and Mapilion (Vector)?

I like this more than showing a warning. Why not remove vector layers entirely, now that we have decided that we like raster tiles better and now that we know that the experience is probably not very nice?

**Comment by karussell** [comment]
> On my iPhone 12 it asks whether it should close the page because it does too much computation

Oh :grin: 

> Why not remove vector layers entirely, now that we have decided that we like raster tiles better and now that we know that the experience is probably not very nice?

My argument was that that "For testing and improving I would keep them. We could then ask / contract e.g. OL maintainers to improve this somehow :)"

But we can also remove them for now.

**Comment by easbar** [comment]
It looks like this now:

![image](https://user-images.githubusercontent.com/17603532/151341622-657d96e6-e160-47c4-b745-1df26b5339b3.png)
