### ISSUE TITLE
Integrate Important Overlays into Web

### ISSUE THREAD

**Issue by karussell** [graphhopper/graphhopper-maps#247]
Some interesting options:

- POI layer
- There is a nice [weather overlay](http://map.comlu.com/openweathermap/?lang=en) showing the current weather in the cities. CC0 licensed
- Also the [turn restriction overlay](http://map.comlu.com/) would be interesting to add. CC0 licensed
- Mapillary. I've also heard about that yandex allows panorama images to be used in OSM (maybe that means we can integrate them in leaflet too)?
- [Traffic layer](http://traffic.arcgis.com/) from ESRI
- Wikipedia articles via [wikipedia api](http://en.wikipedia.org/w/api.php?format=json&action=query&list=geosearch&gsradius=5071.814646526764&gscoord=51.50662276817539|-0.12437813491817451&gslimit=500&callback=jQuery1102037784935597290503_1423776136273&continue=&_=1423776136275) - here is a [google maps example](http://wiki-map.com/map/?locale=en&lat=51.5066&lng=-0.1244) using it

**Comment by Nakaner** [comment]
I [added support](https://github.com/geofabrik/openrailrouting-maps/commit/c66290acaff982dbdb79449c9332f5138d680a51) for overlays in our fork of GraphHopper Maps to be used for OpenRailRouting because I wanted to have OpenRailwayMap tiles as overlays. I can cherry-pick the commit and remove the OpenRailwayMap layers if you would like to add this feature. However, I don't know any good use-case for maps.graphhopper.com.

(The offer to cherry-pick some commits applies to other features, too. For example: configurable links to imprint, privacy policy etc.)
